name: # Action for adservice

on:
    workflow_dispatch: 

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "adservice"
      SERVICE_PATH: "./src/adservice"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: SonarQube Scan
        working-directory: ${{ env.SERVICE_PATH }}
        run: |
          chmod +x ./gradlew
          ./gradlew sonarqube \
            -Dsonar.projectKey=microservices-demo-adservice \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_AUTH_TOKEN }}

  build-and-publish:
    name: Build and Publish Docker Image
    needs: sonarqube
    runs-on: ubuntu-latest
    env:
      SERVICE_NAME: "adservice"
      SERVICE_PATH: "./src/adservice"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} ${{ env.SERVICE_PATH }}

      - name: Trivy Security Scan
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db"
          TRIVY_JAVA_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-java-db"
        run: |
          docker pull public.ecr.aws/aquasecurity/trivy:latest
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e TRIVY_DB_REPOSITORY="${{ env.TRIVY_DB_REPOSITORY }}" \
            -e TRIVY_JAVA_DB_REPOSITORY="${{ env.TRIVY_JAVA_DB_REPOSITORY }}" \
            public.ecr.aws/aquasecurity/trivy:latest image \
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            --severity HIGH,CRITICAL

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.SERVICE_NAME }}:latest

      - name: Clean up Workspace
        if: always()
        run: |
          rm -rf ${{ env.SERVICE_PATH }}y for security scanning
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan on Docker image
        env:
          TRIVY_CACHE_DIR: /tmp/trivycache
        run: trivy image --cache-dir ${{ env.TRIVY_CACHE_DIR }} --scanners vuln maryjane001/adservice:latest

      # build, scan and push adservice
      - name: build adservice image
        run: |
          docker build -t maryjane001/adservice:latest -f ./src/adservice/Dockerfile ./src/adservice/
          docker push maryjane001/adservice:latest

      - name: scan adservice image
        run: |
          trivy image --cache-dir ${{ env.TRIVY_CACHE_DIR }} maryjane001/adservice:latest

      - name: Push adservice image
        run: |
          docker push maryjane001/adservice:latest
