name: Build and Deploy Adservice

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      TRIVY_CACHE_DIR: /tmp/trivycache

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}

      - name: Install Trivy for security scanning
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan on Docker image
        env:
          TRIVY_CACHE_DIR: /tmp/trivycache
        run: trivy image --cache-dir ${{ env.TRIVY_CACHE_DIR }} --scanners vuln maryjane001/adservice:latest

      # build, scan and push adservice
      - name: build adservice image
        run: |
          docker build -t maryjane001/adservice:latest -f ./src/adservice/Dockerfile ./src/adservice/
          docker push maryjane001/adservice:latest

      - name: scan adservice image
        run: |
          trivy image --cache-dir ${{ env.TRIVY_CACHE_DIR }} maryjane001/adservice:latest

      - name: Push adservice image
        run: |
          docker push maryjane001/adservice:latest
